packages:
  - apps/*
  - packages/*

engineStrict: true
strictPeerDependencies: true
saveExact: true
minimumReleaseAgeExclude:
  - '@types/node@24.13.6'
  - eslint@10.11.0
  - mediabunny@1.58.1
allowBuilds:
  esbuild: true
